[project]
name = "uni-lessons-da-and-ml"
version = "0.1.0"
description = "Learning about data analysis and machine learning"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = ["ipykernel>=6.29.5", "pyright>=1.1.400", "ruff>=0.11.7", "uv>=0.6.17"]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = ['T201']

[tool.pyright]
strict = ['src']
